apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-classifier
  namespace: toys
spec:
  selector:
    matchLabels:
      app: query-classifier
  template:
    metadata:
      labels:
        app: query-classifier
    spec:
      containers:
      - name: nlp-dashboard
        image: nlp-dashboard
        resources:
          limits:
            memory: "2Gi"
            cpu: "2"
        ports:
        - containerPort: 8051
        args: ["app.py"]
---
apiVersion: v1
kind: Service
metadata:
  name: query-classifier
  namespace: toys
spec:
  type: LoadBalancer
  selector:
    app: query-classifier
  ports:
  - port: 80
    targetPort: 8051
