apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: sectorsearch
build:
  artifacts:
  - image: nlp-sectorsearch
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s.yaml

profiles:
  - name: nlp-sectorsearch-dev
    activation:
    - kubeContext: nlp-omnisearch-dev
    - command: dev
    deploy:
      kubectl:
        manifests:
          - k8s-dev.yaml
