apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: dashboard
build:
  artifacts:
  - image: nlp-dashboard
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s.yaml
